node {
    def myGradleContainer = docker.image('gradle:jdk8-alpine')
    def GRADLE_HOME = "/var/jenkins_home/.gradle"

    myGradleContainer.pull()

    stage('prep') {
        git url: 'https://github.com/brainshin-star/gs-gradle.git'
    }

    stage('build') {
      myGradleContainer.inside("-v ${GRADLE_HOME}:/home/gradle/.gradle") {
        sh 'cd complete && /opt/gradle/bin/gradle build'
        // sh 'cd complete && gradle test'
      }
    }

    stage('sonar-scanner') {
      def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
      withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
          // sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.language=java -Dsonar.java.binaries=."
          sh "${sonarqubeScannerHome}/bin/sonar-scanner -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.java.binaries=."
          // sh "${sonarqubeScannerHome}/bin/sonar-scanner -Dsonar.host.url=http://172.22.0.3:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.java.binaries=."
          
      }
    }
}
