node {
  stage('do something with git') {  
    sshagent (credentials: ['github-key']) {
      // get the last commit id from a repository you own
      // sh 'git ls-remote -h --refs git@github.com:brainshin-star/jenkins-course.git master |awk "{print $1}"'
      sh 'GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git ls-remote -h --refs git@github.com:brainshin-star/jenkins-course.git master'
    }
  }
}
